Verify the inverse. Multiply A @ A.inverse_2x2() and confirm you get the identity matrix. Try it with three different 2x2 matrices. What happens when the determinant is zero?

In [3]:
import numpy as np
A=np.array([[1,2],[2,3]])
B=np.array([[2,1],[3,3]])
C=np.array([[7,2],[1,3]])
A_inv=np.linalg.inv(A)
B_inv=np.linalg.inv(B)
C_inv=np.linalg.inv(C)
resA=A@A_inv
resA

array([[1., 0.],
       [0., 1.]])

Implement 3x3 inverse. Extend the Matrix class to compute inverses for 3x3 matrices using the adjugate method. Test it against NumPy's np.linalg.inv.

In [16]:
class Matrix:
    def __init__(self, data):
        self.data = [list(row) for row in data]
        self.rows = len(self.data)
        self.cols = len(self.data[0])
        self.shape = (self.rows, self.cols)

    def __repr__(self):
        rows_str = "\n  ".join(str(row) for row in self.data)
        return f"Matrix({self.shape}):\n  {rows_str}"
    
    def determinant(self):
        if self.shape == (1, 1):
            return self.data[0][0]
        if self.shape == (2, 2):
            return self.data[0][0] * self.data[1][1] - self.data[0][1] * self.data[1][0]
        det = 0
        for j in range(self.cols):
            minor = Matrix([
                [self.data[i][k] for k in range(self.cols) if k != j]
                for i in range(1, self.rows)
            ])
            det += ((-1) ** j) * self.data[0][j] * minor.determinant()
        return det
    
    def inverse_2x2(self):
        det = self.determinant()
        if det == 0:
            raise ValueError("Matrix is singular, no inverse exists")
        return Matrix([
            [self.data[1][1] / det, -self.data[0][1] / det],
            [-self.data[1][0] / det, self.data[0][0] / det]
        ])
    
    def get_cofactor_matrix(self,matrix):
        n = matrix.shape[0]
        cofactor = np.zeros((n, n))
        
        for i in range(n):
            for j in range(n):
                # Delete row i and column j to get the minor matrix
                minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
                # Apply the sign (-1)^(i+j) * determinant of minor
                cofactor[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor)
                
        return np.round(cofactor)
    
    def inverse_3x3(self,A):
        det=np.linalg.det(A)
        if det==0:
            raise ValueError("Matrix is singular ,no inverse exists")
        A_inv=(1/det)*self.get_cofactor_matrix(A)
        return A_inv.T
        
    
    

In [18]:

A = np.array([[1, 2, 3],
              [0, 4, 5],
              [1, 0, 6]])
M=Matrix(A)
M.inverse_3x3(A)

array([[ 1.09090909, -0.54545455, -0.09090909],
       [ 0.22727273,  0.13636364, -0.22727273],
       [-0.18181818,  0.09090909,  0.18181818]])

In [19]:
np.linalg.inv(A)

array([[ 1.09090909, -0.54545455, -0.09090909],
       [ 0.22727273,  0.13636364, -0.22727273],
       [-0.18181818,  0.09090909,  0.18181818]])

Build a two-layer network. Using only your Matrix class (no NumPy), create a two-layer neural network: input (3) -> hidden (4) -> output (2). Initialize random weights, run a forward pass, and verify all shapes are correct.

In [27]:
class Matrix:
    def __init__(self, data):
        self.data = [list(row) for row in data]
        self.rows = len(self.data)
        self.cols = len(self.data[0])
        self.shape = (self.rows, self.cols)

    def __repr__(self):
        rows_str = "\n  ".join(str(row) for row in self.data)
        return f"Matrix({self.shape}):\n  {rows_str}"

    def __add__(self, other):
        return Matrix([
            [self.data[i][j] + other.data[i][j] for j in range(self.cols)]
            for i in range(self.rows)
        ])
    
    def __sub__(self,other):
        return Matrix([
            [self.data[i][j]-other.data[i][j] for j in range(self.cols)]
            for i in range(self.rows)
        ])
        
    def scalar_multiply(self,scalar):
        return Matrix([
            [self.data[i][j] *scalar for j in range(self.cols)]
            for i in range(self.rows)
        ])
    
    def element_wise_multiplication(self,other):
        return Matrix([
            [self.data[i][j]*other.data[i][j] for j in range(self.cols)]
            for i in range(self.rows)
        ])
    
    def matmul(self,other):
        return Matrix([
            [
                sum(self.data[i][k]*other.data[k][j] for k in range(self.cols))
            for j in range(other.cols)
            ]
            for i in range(self.rows)
        ])
        
    def transpose(self):
        return Matrix([
            [self.data[j][i] for j in range(self.rows)]
            for i in range(self.cols)
        ])

    def determinant(self):
        if self.shape == (1, 1):
            return self.data[0][0]
        if self.shape == (2, 2):
            return self.data[0][0] * self.data[1][1] - self.data[0][1] * self.data[1][0]
        det = 0
        for j in range(self.cols):
            minor = Matrix([
                [self.data[i][k] for k in range(self.cols) if k != j]
                for i in range(1, self.rows)
            ])
            det += ((-1) ** j) * self.data[0][j] * minor.determinant()
        return det

    def inverse_2x2(self):
        det = self.determinant()
        if det == 0:
            raise ValueError("Matrix is singular, no inverse exists")
        return Matrix([
            [self.data[1][1] / det, -self.data[0][1] / det],
            [-self.data[1][0] / det, self.data[0][0] / det]
        ])

    @staticmethod
    def identity(n):
        return Matrix([
            [1 if i == j else 0 for j in range(n)]
            for i in range(n)
        ])

In [42]:
import random
A = Matrix([[1], [2], [3]])
weights = Matrix([
    [random.uniform(-1, 1) for _ in range(3)]
    for _ in range(4)
])
bias = Matrix([[0.1], [0.1],[0.1],[0.1]])

In [43]:
def relu_matrix(m):
    return Matrix([[max(0, val) for val in row] for row in m.data])


In [50]:
pre_activation = weights.matmul(A) + bias
output1 = relu_matrix(pre_activation)

In [51]:
output1.shape

(4, 1)

In [52]:
weights2 = Matrix([
    [random.uniform(-1, 1) for _ in range(4)]
    for _ in range(2)
])
bias2 = Matrix([[0.1], [0.1]])
z2=weights2.matmul(output1)+bias2
output2=relu_matrix(z2)

In [53]:
output2

Matrix((2, 1)):
  [1.1450188666912586]
  [0.6814564494718792]