In [1]:
z = 3 + 2j
w = 1 + 4j

print(z + w)
print(z * w)
print(abs(z))

import cmath
print(cmath.phase(z))
print(cmath.exp(1j * cmath.pi))

(4+6j)
(-5+14j)
3.605551275463989
0.5880026035475675
(-1+1.2246467991473532e-16j)


In [2]:
import numpy as np

z = np.array([1+2j, 3+4j, 5+6j])
print(np.abs(z))
print(np.angle(z))
print(np.conj(z))
print(np.real(z))
print(np.imag(z))

signal = np.sin(2 * np.pi * 5 * np.linspace(0, 1, 128))
spectrum = np.fft.fft(signal)
freqs = np.fft.fftfreq(128, d=1/128)

[2.23606798 5.         7.81024968]
[1.10714872 0.92729522 0.87605805]
[1.-2.j 3.-4.j 5.-6.j]
[1. 3. 5.]
[2. 4. 6.]
