Implement the full SVD from scratch without using power iteration. Instead, compute the eigendecomposition of A^T A to get V and the singular values, then compute U = A V Sigma^{-1}. Compare numerical accuracy with your power iteration version and with NumPy.

In [1]:
import numpy as np
def svd_from_eigen(A,tol=1e-10):
    m,n=A.shape
    ATA=A.T @ A
    eigenvalues,eigenvectors=np.linalg.eigh(ATA)
    idx=np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[idx]
    V = eigenvectors[:, idx]
    eigenvalues = np.maximum(eigenvalues, 0)
    singular_values = np.sqrt(eigenvalues)
    rank = np.sum(singular_values > tol)
    S = singular_values[:rank]
    V = V[:, :rank]
    U = (A @ V) / S

    return U, S, V.T

In [2]:
A = np.array([
    [1, 1],
    [2, 1],
    [3, 1]
], dtype=float)

In [4]:
U, S, Vt = svd_from_eigen(A)

print("U:")
print(U)

print("\nS:")
print(S)

print("\nVt:")
print(Vt)

U:
[[-0.32310986 -0.85377594]
 [-0.54750702 -0.18321952]
 [-0.77190419  0.4873369 ]]

S:
[4.07914333 0.60049122]

Vt:
[[-0.91534819 -0.40266324]
 [ 0.40266324 -0.91534819]]


In [5]:
A_reconstructed = U @ np.diag(S) @ Vt

print("\nOriginal A:")
print(A)

print("\nReconstructed A:")
print(A_reconstructed)


Original A:
[[1. 1.]
 [2. 1.]
 [3. 1.]]

Reconstructed A:
[[1. 1.]
 [2. 1.]
 [3. 1.]]


In [6]:
# NumPy SVD
U_np, S_np, Vt_np = np.linalg.svd(
    A,
    full_matrices=False
)

# Our SVD
U_eig, S_eig, Vt_eig = svd_from_eigen(A)

print("Our singular values:")
print(S_eig)

print("\nNumPy singular values:")
print(S_np)

Our singular values:
[4.07914333 0.60049122]

NumPy singular values:
[4.07914333 0.60049122]
